services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alquiler-app
    ports:
      - "0.0.0.0:8082:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: always
    networks:
      - alquiler-network

  db:
    image: mysql:8.0
    container_name: alquiler-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - alquiler-network

networks:
  alquiler-network:
    driver: bridge

volumes:
  db-data:
